User.create(name: 'akku', password: 'admin')
User.create(name: 'abhi', password: 'admin')
User.create(name: 'jo', password: 'admin')
User.create(name: 'anju', password: 'admin')
User.create(name: 'admin', password: 'admin')
